//** LAYOUT **//
export const TOGGLE_SIDEBAR = '[MD][SIDEBAR] TOGGLE_TODO';
export const TOGGLE_FORM = '[MD][FORM] TOGGLE_FORM';
export const CLOSE_FORM = '[MD][FORM] CLOSE_FORM';
export const OPEN_FORM = '[MD][FORM] OPEN_FORM';
export const OPEN_SEARCH = '[MD][FORM] OPEN_SEARCH';
export const CLOSE_SEARCH = '[MD][FORM] CLOSE_SEARCH';
export const TOGGLE_SEARCH = '[MD][FORM] TOGGLE_SEARCH';

//** DATA-CONTROL-COMMON **//
export const DATA_RECIVED = '[MD][DATA] DATA_RECIVED';
export const REQUEST_SENT = '[MD][DATA] REQUEST_SENT';

//** DATA-CONTROL-MOVIES **//
export const INIT_MOVIES = '[MD][DATA] INIT_MOVIES';
export const INITED_MOVIES = '[MD][DATA] INITED_MOVIES';
export const FILTER_MOVIES_BY_NAME = '[MD][DATA] FILTER_MOVIES_BY_NAME';
export const ADD_MOVIE = '[MD][DATA] ADD_MOVIE';
export const FILTER_MOVIES_ADVANCED = '[MD][DATA] FILTER_MOVIES_ADVANCED';

//** DATA-CONTROL-TV-SHOWS **//
export const INIT_TV_SHOWS = '[MD][DATA] INIT_TV_SHOWS';
export const INITED_TV_SHOWS = '[MD][DATA] INITED_TV_SHOWS';
export const FILTER_TV_SHOWS_BY_NAME = '[MD][DATA] FILTER_TV_SHOWS_BY_NAME';
export const ADD_TV_SHOW = '[MD][DATA] ADD_TV_SHOW';
export const FILTER_TV_SHOWS_ADVANCED = '[MD][DATA] FILTER_TV_SHOWS_ADVANCED';

//** DATA-CONTROL-GENRES **//
export const INIT_GENRES = '[MD][DATA] INIT_GENRES';
export const INITED_GENRES = '[MD][DATA] INITED_GENRES';

//** DATA-CONTROL-MYLIB **//
export const INIT_MYLIB = '[MD][DATA] INIT_MYLIB';
export const SAVE_ITEM = '[MD][DATA] SAVE_ITEM';
export const DELETE_ITEM = '[MD][DATA] DELETE_ITEM';
export const FILTER_ITEMS_BY_NAME = '[MD][DATA] FILTER_ITEMS_BY_NAME';
export const FILTER_ITEMS_ADVANCED = '[MD][DATA] FILTER_ITEMS_ADVANCED';
export const WATCH_ALL_ITEMS = '[MD][DATA] WATCH_ALL_ITEMS';


